Assets/New Universal Render Pipeline Asset_Renderer.asset
Assets/Prefabs/ApplyLightMaterial.mat
Assets/Prefabs/ApplyLightMaterial.mat.meta
Assets/Prefabs/Boss_01.prefab
Assets/Prefabs/Chest.prefab
Assets/Prefabs/Portal.prefab
Assets/Prefabs/Small Crate.prefab
Assets/Prefabs/SmallEnemy.prefab
Assets/Prefabs/Torch.prefab
Assets/Scenes/Dungeon1.unity
Assets/Scenes/Main.unity

- Added the renderer into the project settings.
- Material for rendering saved in prefab folder and applied to prefabs and current dungeon entities
- Global light added to current dungeons 
- Spotlight added under player

Added global light, material to prefabs, and spotlight on player

---

Assets/Artwork/Atlas_2.png.meta
Assets/Artwork/Icon_Atlas.png.meta
Assets/Artwork/WoodenSwordSet-Sheet.png.meta
Assets/Scenes/Main.unity
Assets/Scripts/Chest.cs
Assets/Scripts/CollectableItem.cs
Assets/Scripts/CollectableItemStruct.cs
Assets/Scripts/GameManager.cs
Assets/Scripts/Inventory.cs
Assets/Scripts/PlayerData.cs
Assets/Scripts/SpriteData.cs
Assets/Scripts/SpriteData.cs.meta

- Sprites saving and loading for item images in inventory
- Stopping players from picking-up more items when inventory is full, displaying appropriate 'INVENTORY FULL' text, and not opening the chest.

15 03 2023 saving item sprites

---

Assets/Scenes/Main.unity
Assets/Scripts/DragDrop.cs
Assets/Scripts/DragDrop.cs.meta
Assets/Scripts/EquippedInventory.cs
Assets/Scripts/EquippedInventory.cs.meta
Assets/Scripts/Inventory.cs
Assets/Scripts/InventoryMenu.cs
Assets/Scripts/ItemSlot.cs
Assets/Scripts/ItemSlot.cs.meta
Assets/Scripts/Player.cs

- inventory management / organisation (drag and drop)
- equipping items onto player

17 03 2023 drag drop UI

---

Assets/Scenes/Main.unity
Assets/Scripts/DragDrop.cs
Assets/Scripts/EquippedInventory.cs
Assets/Scripts/GameManager.cs
Assets/Scripts/Inventory.cs
Assets/Scripts/InventoryMenu.cs
Assets/Scripts/ItemSlot.cs
Assets/Scripts/PlayerData.cs

Fixed main bugs with drag drop inventory system
Implemented saving and loading of current weapon and armour

19 03 2023 drag drop inventory continued

---

Assets/Scenes/Main.unity
Assets/Scripts/Chest.cs
Assets/Scripts/DragDrop.cs
Assets/Scripts/GameManager.cs

Fixed item duplication bug from chests and InventoryMenu not deleting upon load of new scene

19 03 2023 item pick up duplication bug fix

---

Assets/Artwork/Icon_Atlas.png.meta
Assets/Prefabs/OnHitParticleSystem.prefab
Assets/Resources/Animations/AdventurerDiary.controller
Assets/Resources/Animations/AdventurerDiary.controller.meta
Assets/Resources/Animations/AdventurerDiary_hiding.anim
Assets/Resources/Animations/AdventurerDiary_hiding.anim.meta
Assets/Resources/Animations/AdventurerDiary_showing.anim
Assets/Resources/Animations/AdventurerDiary_showing.anim.meta
Assets/Scenes/Main.unity
Assets/Scripts/AdventurerDiary.cs
Assets/Scripts/AdventurerDiary.cs.meta
Assets/Scripts/Enemy.cs
Assets/Scripts/GameManager.cs

Added:
- Adventurer Diary
-  Tabs
-  Pages
- Tracking enemy deaths

19 03 2023 adventurer diary feature

---

Assets/Scripts/AdventurerDiary.cs
Assets/Scripts/GameManager.cs
Assets/Scripts/PlayerData.cs

Added:
- Saving and loading for enemies defeated list
Fixed:
- Multiple instances of the adventurer book created when dungeon revisited

Defeated Enemies saved and loaded, only one adventure book per instance

---

Assets/Scripts/GameManager.cs

Fixed:
- Calling OnHealthChange() in gamemanager upon loading in the player health

Calling health bar update on loading in health

---

Assets/Prefabs/OnHitParticleSystem.prefab
Assets/Scripts/EnemyHitbox.cs
Assets/Scripts/Fighter.cs
Assets/Scripts/Player.cs

- Immunity for player removed
- Enemy attack cooldowns added

22 03 2023 enemy attack cooldowns

---

Assets/Scenes/Main.unity
Assets/Scripts/Enemy.cs
Assets/Scripts/EnemyHitbox.cs
Assets/Scripts/Mover.cs
Assets/Scripts/Player.cs

Staggering feature implemented for movers

22 03 2023 stagger enemies

---

Assets/Resources/Animations/Player_2.controller
Assets/Resources/Animations/Player_Hands.controller
Assets/Resources/Animations/Weapon.controller
Assets/Resources/Animations/weapon_walk_down.anim
Assets/Scenes/Main.unity
Assets/Scripts/ChaseState.cs
Assets/Scripts/ChaseState.cs.meta
Assets/Scripts/Enemy.cs
Assets/Scripts/IState.cs
Assets/Scripts/IState.cs.meta
Assets/Scripts/IdleState.cs
Assets/Scripts/IdleState.cs.meta
Assets/Scripts/Mover.cs
Assets/Scripts/ReturnState.cs
Assets/Scripts/ReturnState.cs.meta
Assets/Scripts/StateMachine.cs
Assets/Scripts/StateMachine.cs.meta

Added:
- StateMachine, state interface, and working state flow for small enemies

Added state machine basics for small enemy

---

Assets/Resources/Animations/Player_2.controller
Assets/Resources/Animations/Player_Hands.controller
Assets/Resources/Animations/Weapon.controller
Assets/Resources/Animations/kuba_walking_up.anim
Assets/Resources/Animations/player_hands_walking_up.anim
Assets/Resources/Animations/weapon_walk_up.anim

Added:
- Kuba_walking_up animation
-player_hands_walking_up
-weapon_walking_up

Added upward walking and set default back to idle

---

Assets/Scripts/Weapon.cs

Fixed:
- continual collision with enemy upon weapon swing

fixed weapon swing bug

---

Assets/Scenes/ProceduralScene1.unity
Assets/Scripts/PropPlacementManager.cs
Assets/Scripts/TilemapVisualiser.cs

each dungeon style will use its own set of props

Prop selection separated into lists 

---

Assets/Artwork/_Sprites/Dungeon Tilesets/Atlas.png.meta
Assets/Scenes/ProceduralScene1.unity
Assets/Scripts/Data/Props/StackedCrate.asset
Assets/Scripts/Data/Props/StackedCrate.asset.meta
Assets/Scripts/Data/Props/StackedCrateBottom.asset
Assets/Scripts/Data/Props/StackedCrateBottom.asset.meta
Assets/Scripts/Data/Props/StackedCrateTop.asset
Assets/Scripts/Data/Props/StackedCrateTop.asset.meta
Assets/Scripts/Data/Props/Vase0Prop.asset

Added:
- composite prop for stacked crate objects
- Adjusted offset to 0.15 vs 0.16 to reduce gap between sprites on different layers

Added compositeprop for stacked crates

---

Assets/Scripts/CorridorFirstDungeonGenerator.cs
Assets/Scripts/RoomDataExtractor.cs
Assets/Scripts/RoomsFirstDungeonGenerator.cs
Assets/Scripts/SimpleRandomWalkDungeonGenerator.cs
Assets/Scripts/WallGenerator.cs

created new basic wall thin for simplerandomwalk

Fixed random colliders and gaps in Random Walk

---

Assets/Scripts/Player.cs

Fixed:
-Stuck dashing during death animation

Manually turn off dash upon death

---

Assets/Artwork/_Sprites/Dungeon Tilesets/Dungeon_Tileset.png.meta
Assets/Prefabs/Enemy/Bosses/Boss_01.prefab
Assets/Scenes/Main.unity
Assets/Scenes/ProceduralScene1.unity
Assets/Scripts/AgentPlacementManager.cs
Assets/Scripts/DroppedItem.cs
Assets/Scripts/KeyLockedPortal.cs
Assets/Scripts/KeyLockedPortal.cs.meta
Assets/Scripts/Portal.cs
Assets/Scripts/PropPlacementManager.cs

Boss drops key.
Key required to use the escape portal out of the dungeon.
Key used (removed) upon use.

25 04 2023 boss drops exit key

---

Assets/Scenes/MainMenu.unity
Assets/Scripts/MainMenuManager.cs
Assets/Scripts/MainMenuManager.cs.meta

Play button loads Main scene
Exit button quits game

27 04 2023 main menu play function

---

Assets/Resources/Animations/Player_2.controller
Assets/Resources/Animations/Player_Hands.controller
Assets/Resources/Animations/Weapon.controller
Assets/Resources/Animations/weapon_combo_swipe_1_down.anim
Assets/Resources/Animations/weapon_combo_swipe_1_down.anim.meta
Assets/Resources/Animations/weapon_combo_swipe_1_left.anim
Assets/Resources/Animations/weapon_combo_swipe_1_left.anim.meta
Assets/Resources/Animations/weapon_combo_swipe_1_right.anim
Assets/Resources/Animations/weapon_combo_swipe_1_right.anim.meta
Assets/Resources/Animations/weapon_combo_swipe_1_up.anim
Assets/Resources/Animations/weapon_combo_swipe_1_up.anim.meta
Assets/Resources/Animations/weapon_combo_swipe_2_down.anim
Assets/Resources/Animations/weapon_combo_swipe_2_down.anim.meta
Assets/Resources/Animations/weapon_combo_swipe_2_left.anim
Assets/Resources/Animations/weapon_combo_swipe_2_left.anim.meta
Assets/Resources/Animations/weapon_combo_swipe_2_right.anim
Assets/Resources/Animations/weapon_combo_swipe_2_right.anim.meta
Assets/Resources/Animations/weapon_combo_swipe_2_up.anim
Assets/Resources/Animations/weapon_combo_swipe_2_up.anim.meta

Added
- Sword combo animations for all directions

Added sword combo animations for each direction
